### ISSUE TITLE
inputplug does not compile on FreeBSD 14.0-CURRENT amd64

### ISSUE THREAD

**Issue by 0mp** [andrewshadura/inputplug#10]
The problem seems to be the [pidfile-rs](https://github.com/andrewshadura/bsd-pidfile-rs) crate. I've reported the problem upstream (see https://github.com/andrewshadura/bsd-pidfile-rs/issues/4). I'm just giving you a heads-up that release 0.4.0 does not seem to compile on FreeBSD.

**Comment by andrewshadura** [comment]
Since the issue with pidfile-rs has been fixed, I’m closing this.
