### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by funollet** [andrewshadura/inputplug#12]
(Disclaimer: I don't have experience with Rust).

I'm trying to build the project but I get an error about missing dependencies. I set up a github action to make it easier to reproduce. Here's the log:

https://github.com/funollet/inputplug/actions/runs/3173138634/jobs/5168413528

**Comment by andrewshadura** [comment]
You need to either build without `pidfile` feature, or install `libbsd-dev`.

**Comment by funollet** [comment]
That worked. Thanks!
