### ISSUE TITLE
signal.h is missing on FreeBSD

### ISSUE THREAD

**Issue by 0mp** [andrewshadura/inputplug#6]
Hi there!

I've just ported inputplug to FreeBSD (https://www.freshports.org/x11/inputplug/) and I noticed that the signal.h header is missing. I am not sure how to detect it using mk-configure so I've not submitted a PR for that. Currently, we just have a patch like this in the ports tree: https://svnweb.freebsd.org/ports/head/x11/inputplug/files/patch-inputplug.c?view=markup&pathrev=551917

Cheers!

**Comment by jbeich** [comment]
DragonFly needs a similar fix, see https://github.com/DragonFlyBSD/DeltaPorts/commit/d9a528ade23b

Why not include `<signal.h>` unconditionally? It's available on all POSIX systems.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html

**Comment by 0mp** [comment]
> Why not include `<signal.h>` unconditionally? It's available on all POSIX systems.
> https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html

Oh, I've not thought about checking that. It makes sense.

**Comment by andrewshadura** [comment]
Closing as signal.h is no longer used.
